/* Vocabulary content — categorized "vocabulary sheets" by subject.
   Source: Sakura Speak official Vocabulary Lists (107-page set).
   Japanese in the source PDF is not machine-extractable, so sheets are
   transcribed (kanji + kana + romaji + English) in batches via OCR.
   Subjects with words: [] are listed but not yet transcribed ("coming soon"). */

export type Word = { jp: string; kanji?: string; romaji: string; en: string };

export type Subject = { slug: string; label: string; words: Word[] };

export type VocabCategory = {
  slug: string;
  label: string;
  emoji: string;
  accent: "pink" | "blue" | "mint" | "gold" | "lilac";
  subjects: Subject[];
};

const slug = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

// coming-soon subjects (names only)
const soon = (...names: string[]): Subject[] =>
  names.map((n) => ({ slug: slug(n), label: n, words: [] }));

// populated subject
const sheet = (label: string, words: Word[]): Subject => ({
  slug: slug(label),
  label,
  words,
});

export const vocabCategories: VocabCategory[] = [
  {
    slug: "home",
    label: "Home & Daily Life",
    emoji: "🏠",
    accent: "pink",
    subjects: [
      sheet("Living Room", [
        { kanji: "居間", jp: "いま", romaji: "ima", en: "Living room (formal)" },
        { jp: "リビング", romaji: "ribingu", en: "Living room (casual)" },
        { jp: "ソファ", romaji: "sofa", en: "Sofa / couch" },
        { kanji: "椅子", jp: "いす", romaji: "isu", en: "Chair" },
        { jp: "テーブル", romaji: "teeburu", en: "Table" },
        { jp: "カーペット", romaji: "kaapetto", en: "Carpet / rug" },
        { jp: "クッション", romaji: "kusshon", en: "Cushion" },
        { jp: "テレビ", romaji: "terebi", en: "TV" },
        { jp: "リモコン", romaji: "rimokon", en: "Remote control" },
        { kanji: "本棚", jp: "ほんだな", romaji: "hondana", en: "Bookshelf" },
        { kanji: "絵", jp: "え", romaji: "e", en: "Painting / picture" },
        { kanji: "時計", jp: "とけい", romaji: "tokei", en: "Clock" },
        { kanji: "照明", jp: "しょうめい", romaji: "shoumei", en: "Lighting" },
        { jp: "ランプ", romaji: "ranpu", en: "Lamp" },
        { kanji: "観葉植物", jp: "かんようしょくぶつ", romaji: "kanyou shokubutsu", en: "Houseplant" },
        { jp: "カーテン", romaji: "kaaten", en: "Curtain" },
        { kanji: "窓", jp: "まど", romaji: "mado", en: "Window" },
        { jp: "エアコン", romaji: "eakon", en: "Air conditioner" },
        { kanji: "扇風機", jp: "せんぷうき", romaji: "senpuuki", en: "Electric fan" },
        { kanji: "暖房", jp: "だんぼう", romaji: "danbou", en: "Heater" },
        { kanji: "棚", jp: "たな", romaji: "tana", en: "Shelf" },
        { kanji: "写真", jp: "しゃしん", romaji: "shashin", en: "Photograph" },
        { kanji: "電気", jp: "でんき", romaji: "denki", en: "Light / electricity" },
        { jp: "コンセント", romaji: "konsento", en: "Outlet" },
        { kanji: "電源コード", jp: "でんげんコード", romaji: "dengen koodo", en: "Power cord" },
        { jp: "スピーカー", romaji: "supiikaa", en: "Speaker" },
      ]),
      sheet("Kitchen", [
        { kanji: "台所", jp: "だいどころ", romaji: "daidokoro", en: "Kitchen" },
        { jp: "キッチン", romaji: "kicchin", en: "Kitchen (casual)" },
        { kanji: "冷蔵庫", jp: "れいぞうこ", romaji: "reizouko", en: "Refrigerator" },
        { kanji: "冷凍庫", jp: "れいとうこ", romaji: "reitouko", en: "Freezer" },
        { kanji: "電子レンジ", jp: "でんしレンジ", romaji: "denshi renji", en: "Microwave" },
        { kanji: "炊飯器", jp: "すいはんき", romaji: "suihanki", en: "Rice cooker" },
        { jp: "オーブン", romaji: "oobun", en: "Oven" },
        { jp: "トースター", romaji: "toosutaa", en: "Toaster" },
        { kanji: "電気ケトル", jp: "でんきケトル", romaji: "denki ketoru", en: "Electric kettle" },
        { jp: "コンロ", romaji: "konro", en: "Stovetop / burner" },
        { jp: "フライパン", romaji: "furaipan", en: "Frying pan" },
        { kanji: "鍋", jp: "なべ", romaji: "nabe", en: "Pot" },
        { kanji: "包丁", jp: "ほうちょう", romaji: "houchou", en: "Kitchen knife" },
        { kanji: "まな板", jp: "まないた", romaji: "manaita", en: "Cutting board" },
        { kanji: "お玉", jp: "おたま", romaji: "otama", en: "Ladle" },
        { kanji: "菜箸", jp: "さいばし", romaji: "saibashi", en: "Cooking chopsticks" },
        { jp: "ボウル", romaji: "bouru", en: "Bowl" },
        { jp: "ざる", romaji: "zaru", en: "Strainer / colander" },
        { kanji: "計量カップ", jp: "けいりょうカップ", romaji: "keiryou kappu", en: "Measuring cup" },
        { kanji: "計量スプーン", jp: "けいりょうスプーン", romaji: "keiryou supuun", en: "Measuring spoon" },
      ]),
      ...soon(
        "Bathroom & Laundry", "Bedroom", "Appliances & Electronics", "Furniture",
        "Cleaning Supplies & Chores", "Tools & Fixing Things", "Housing Types & Renting"
      ),
    ],
  },
  {
    slug: "shopping",
    label: "Shopping & Retail",
    emoji: "🛍️",
    accent: "lilac",
    subjects: [
      sheet("Supermarket Phrases", [
        { jp: "いらっしゃいませ", romaji: "irasshaimase", en: "Welcome (store greeting)" },
        { kanji: "袋はいりますか", jp: "ふくろはいりますか", romaji: "fukuro wa irimasu ka", en: "Do you need a bag?" },
        { kanji: "レジ袋", jp: "レジぶくろ", romaji: "reji bukuro", en: "Plastic checkout bag" },
        { jp: "ポイントカード", romaji: "pointo kaado", en: "Point / loyalty card" },
        { kanji: "温めますか", jp: "あたためますか", romaji: "atatamemasu ka", en: "Shall I heat this up?" },
        { kanji: "試食", jp: "ししょく", romaji: "shishoku", en: "Food sample / tasting" },
        { kanji: "半額", jp: "はんがく", romaji: "hangaku", en: "Half price" },
        { kanji: "本日のお買い得品", jp: "ほんじつのおかいどくひん", romaji: "honjitsu no okaidoku hin", en: "Today's bargain items" },
        { jp: "おつり", romaji: "otsuri", en: "Change (money)" },
        { kanji: "領収書", jp: "りょうしゅうしょ", romaji: "ryoushuusho", en: "Receipt" },
      ]),
      ...soon(
        "Clothes Shopping", "Shoe Shopping", "Bags & Accessories", "Jewelry & Watches",
        "Makeup & Skincare", "Sizes, Patterns & Materials", "Describing Items",
        "At the Register / Checkout", "Department Store Floors", "Thrift Shopping"
      ),
    ],
  },
  {
    slug: "food",
    label: "Food & Dining",
    emoji: "🍽️",
    accent: "gold",
    subjects: [
      sheet("Fancy Restaurant", [
        { kanji: "予約", jp: "よやく", romaji: "yoyaku", en: "Reservation" },
        { kanji: "コース料理", jp: "コースりょうり", romaji: "koosu ryouri", en: "Course meal" },
        { kanji: "前菜", jp: "ぜんさい", romaji: "zensai", en: "Appetizer" },
        { jp: "メインディッシュ", romaji: "mein disshu", en: "Main dish" },
        { jp: "デザート", romaji: "dezaato", en: "Dessert" },
        { jp: "ワインリスト", romaji: "wain risuto", en: "Wine list" },
        { jp: "ソムリエ", romaji: "somurie", en: "Sommelier" },
        { kanji: "個室", jp: "こしつ", romaji: "koshitsu", en: "Private room" },
        { kanji: "窓側の席", jp: "まどがわのせき", romaji: "madogawa no seki", en: "Window seat" },
      ]),
      sheet("Fruits", [
        { kanji: "果物", jp: "くだもの", romaji: "kudamono", en: "Fruit (general)" },
        { jp: "りんご", romaji: "ringo", en: "Apple" },
        { jp: "みかん", romaji: "mikan", en: "Mandarin orange" },
        { jp: "バナナ", romaji: "banana", en: "Banana" },
        { jp: "ぶどう", romaji: "budou", en: "Grapes" },
        { jp: "マスカット", romaji: "masukatto", en: "Muscat / green grapes" },
        { jp: "もも", romaji: "momo", en: "Peach" },
        { jp: "いちご", romaji: "ichigo", en: "Strawberry" },
        { jp: "すいか", romaji: "suika", en: "Watermelon" },
        { jp: "メロン", romaji: "meron", en: "Melon" },
        { jp: "なし", romaji: "nashi", en: "Pear (Asian pear)" },
        { jp: "さくらんぼ", romaji: "sakuranbo", en: "Cherry" },
        { jp: "パイナップル", romaji: "painappuru", en: "Pineapple" },
        { jp: "キウイ", romaji: "kiui", en: "Kiwi" },
        { jp: "レモン", romaji: "remon", en: "Lemon" },
        { jp: "グレープフルーツ", romaji: "gureepufuruutsu", en: "Grapefruit" },
        { jp: "ライム", romaji: "raimu", en: "Lime" },
        { jp: "マンゴー", romaji: "mangoo", en: "Mango" },
        { jp: "アボカド", romaji: "abokado", en: "Avocado" },
        { kanji: "柿", jp: "かき", romaji: "kaki", en: "Persimmon" },
        { kanji: "栗", jp: "くり", romaji: "kuri", en: "Chestnut" },
        { jp: "ブルーベリー", romaji: "buruuberii", en: "Blueberry" },
        { jp: "ラズベリー", romaji: "razuberii", en: "Raspberry" },
        { jp: "ブラックベリー", romaji: "burakkuberii", en: "Blackberry" },
        { jp: "ココナッツ", romaji: "kokonattsu", en: "Coconut" },
        { jp: "ドリアン", romaji: "dorian", en: "Durian" },
        { jp: "ドラゴンフルーツ", romaji: "doragon furuutsu", en: "Dragon fruit" },
        { jp: "パッションフルーツ", romaji: "passhon furuutsu", en: "Passion fruit" },
      ]),
      sheet("Vegetables", [
        { kanji: "野菜", jp: "やさい", romaji: "yasai", en: "Vegetables" },
        { jp: "にんじん", romaji: "ninjin", en: "Carrot" },
        { jp: "じゃがいも", romaji: "jagaimo", en: "Potato" },
        { jp: "さつまいも", romaji: "satsumaimo", en: "Sweet potato" },
        { jp: "たまねぎ", romaji: "tamanegi", en: "Onion" },
        { jp: "ねぎ", romaji: "negi", en: "Green onion / scallion" },
        { jp: "にんにく", romaji: "ninniku", en: "Garlic" },
        { jp: "しょうが", romaji: "shouga", en: "Ginger" },
        { jp: "だいこん", romaji: "daikon", en: "Daikon radish" },
        { jp: "れんこん", romaji: "renkon", en: "Lotus root" },
        { jp: "ごぼう", romaji: "gobou", en: "Burdock root" },
        { jp: "キャベツ", romaji: "kyabetsu", en: "Cabbage" },
        { jp: "レタス", romaji: "retasu", en: "Lettuce" },
        { jp: "はくさい", romaji: "hakusai", en: "Napa cabbage" },
        { jp: "ほうれんそう", romaji: "hourensou", en: "Spinach" },
        { jp: "チンゲンサイ", romaji: "chingensai", en: "Bok choy" },
        { jp: "ブロッコリー", romaji: "burokkorii", en: "Broccoli" },
        { jp: "カリフラワー", romaji: "karifurawaa", en: "Cauliflower" },
        { jp: "トマト", romaji: "tomato", en: "Tomato" },
        { jp: "きゅうり", romaji: "kyuuri", en: "Cucumber" },
        { jp: "なす", romaji: "nasu", en: "Eggplant" },
        { jp: "ピーマン", romaji: "piiman", en: "Green bell pepper" },
        { jp: "パプリカ", romaji: "papurika", en: "Paprika / sweet pepper" },
        { jp: "えだまめ", romaji: "edamame", en: "Edamame" },
        { jp: "とうもろこし", romaji: "toumorokoshi", en: "Corn" },
        { jp: "かぼちゃ", romaji: "kabocha", en: "Pumpkin / squash" },
        { jp: "ズッキーニ", romaji: "zukkiini", en: "Zucchini" },
        { jp: "もやし", romaji: "moyashi", en: "Bean sprouts" },
        { jp: "きのこ", romaji: "kinoko", en: "Mushroom" },
        { jp: "しいたけ", romaji: "shiitake", en: "Shiitake mushroom" },
      ]),
      sheet("Seafood", [
        { kanji: "魚介類", jp: "ぎょかいるい", romaji: "gyokairui", en: "Seafood" },
        { kanji: "魚", jp: "さかな", romaji: "sakana", en: "Fish" },
        { kanji: "鮭", jp: "さけ", romaji: "sake", en: "Salmon" },
        { jp: "サーモン", romaji: "saamon", en: "Salmon (sashimi)" },
        { jp: "まぐろ", romaji: "maguro", en: "Tuna" },
        { kanji: "赤身", jp: "あかみ", romaji: "akami", en: "Lean tuna (red meat)" },
        { jp: "中トロ", romaji: "chuutoro", en: "Medium-fatty tuna" },
        { jp: "大トロ", romaji: "ootoro", en: "Fatty tuna" },
        { jp: "かつお", romaji: "katsuo", en: "Skipjack / bonito" },
        { jp: "ぶり", romaji: "buri", en: "Yellowtail" },
        { jp: "いか", romaji: "ika", en: "Squid" },
        { jp: "たこ", romaji: "tako", en: "Octopus" },
        { jp: "えび", romaji: "ebi", en: "Shrimp" },
        { jp: "かに", romaji: "kani", en: "Crab" },
        { jp: "ほたて", romaji: "hotate", en: "Scallop" },
        { jp: "あさり", romaji: "asari", en: "Clam" },
        { jp: "しじみ", romaji: "shijimi", en: "Freshwater clam" },
        { jp: "かき", romaji: "kaki", en: "Oyster" },
        { jp: "うに", romaji: "uni", en: "Sea urchin" },
        { jp: "いくら", romaji: "ikura", en: "Salmon roe" },
        { jp: "たらこ", romaji: "tarako", en: "Cod roe" },
        { kanji: "海藻", jp: "かいそう", romaji: "kaisou", en: "Seaweed" },
        { jp: "わかめ", romaji: "wakame", en: "Soft edible seaweed" },
        { jp: "のり", romaji: "nori", en: "Dried seaweed (nori)" },
      ]),
      sheet("Drinks", [
        { kanji: "飲み物", jp: "のみもの", romaji: "nomimono", en: "Drinks / beverages" },
        { kanji: "水", jp: "みず", romaji: "mizu", en: "Water" },
        { kanji: "炭酸水", jp: "たんさんすい", romaji: "tansansui", en: "Sparkling water" },
        { kanji: "お茶", jp: "おちゃ", romaji: "ocha", en: "Tea" },
        { kanji: "緑茶", jp: "りょくちゃ", romaji: "ryokucha", en: "Green tea" },
        { kanji: "麦茶", jp: "むぎちゃ", romaji: "mugicha", en: "Roasted barley tea" },
        { kanji: "ほうじ茶", jp: "ほうじちゃ", romaji: "houjicha", en: "Roasted green tea" },
        { kanji: "ウーロン茶", jp: "ウーロンちゃ", romaji: "uuron cha", en: "Oolong tea" },
        { jp: "ミルクティー", romaji: "miruku tii", en: "Milk tea" },
        { jp: "コーヒー", romaji: "koohii", en: "Coffee" },
        { jp: "アイスコーヒー", romaji: "aisu koohii", en: "Iced coffee" },
        { jp: "カフェラテ", romaji: "kafe rate", en: "Café latte" },
        { jp: "カプチーノ", romaji: "kapuchiino", en: "Cappuccino" },
        { jp: "エスプレッソ", romaji: "esupuresso", en: "Espresso" },
        { jp: "ココア", romaji: "kokoa", en: "Hot chocolate / cocoa" },
        { jp: "ジュース", romaji: "juusu", en: "Juice" },
        { jp: "オレンジジュース", romaji: "orenji juusu", en: "Orange juice" },
        { jp: "りんごジュース", romaji: "ringo juusu", en: "Apple juice" },
        { jp: "野菜ジュース", kanji: "野菜ジュース", romaji: "yasai juusu", en: "Vegetable juice" },
        { jp: "ソーダ", romaji: "sooda", en: "Soda" },
        { jp: "コーラ", romaji: "koora", en: "Cola" },
        { jp: "ラムネ", romaji: "ramune", en: "Ramune (Japanese soda)" },
        { jp: "エナジードリンク", romaji: "enajii dorinku", en: "Energy drink" },
        { kanji: "豆乳", jp: "とうにゅう", romaji: "tounyuu", en: "Soy milk" },
        { kanji: "お酒", jp: "おさけ", romaji: "osake", en: "Alcohol / sake" },
        { kanji: "日本酒", jp: "にほんしゅ", romaji: "nihonshu", en: "Sake (rice wine)" },
        { kanji: "焼酎", jp: "しょうちゅう", romaji: "shouchuu", en: "Shochu" },
        { jp: "ビール", romaji: "biiru", en: "Beer" },
        { jp: "生ビール", kanji: "生ビール", romaji: "nama biiru", en: "Draft beer" },
        { jp: "ハイボール", romaji: "haibooru", en: "Highball" },
        { jp: "レモンサワー", romaji: "remon sawaa", en: "Lemon sour" },
        { jp: "チューハイ", romaji: "chuuhai", en: "Chu-hi" },
        { jp: "カクテル", romaji: "kakuteru", en: "Cocktail" },
        { jp: "ウイスキー", romaji: "uisukii", en: "Whisky" },
        { jp: "ワイン", romaji: "wain", en: "Wine" },
        { kanji: "赤ワイン", jp: "あかワイン", romaji: "aka wain", en: "Red wine" },
        { kanji: "白ワイン", jp: "しろワイン", romaji: "shiro wain", en: "White wine" },
        { jp: "シャンパン", romaji: "shanpan", en: "Champagne" },
        { kanji: "梅酒", jp: "うめしゅ", romaji: "umeshu", en: "Plum wine (umeshu)" },
      ]),
      sheet("Desserts & Sweets", [
        { kanji: "甘いもの", jp: "あまいもの", romaji: "amaimono", en: "Sweets / sweet things" },
        { jp: "デザート", romaji: "dezaato", en: "Dessert" },
        { jp: "スイーツ", romaji: "suiitsu", en: "Sweets" },
        { kanji: "和菓子", jp: "わがし", romaji: "wagashi", en: "Traditional Japanese sweets" },
        { kanji: "団子", jp: "だんご", romaji: "dango", en: "Dumplings on a stick" },
        { jp: "あんこ", romaji: "anko", en: "Sweet red bean paste" },
        { kanji: "大福", jp: "だいふく", romaji: "daifuku", en: "Mochi with filling" },
        { kanji: "いちご大福", jp: "いちごだいふく", romaji: "ichigo daifuku", en: "Strawberry daifuku" },
        { kanji: "たい焼き", jp: "たいやき", romaji: "taiyaki", en: "Fish-shaped filled cake" },
        { kanji: "どら焼き", jp: "どらやき", romaji: "dorayaki", en: "Red-bean pancake sandwich" },
        { kanji: "羊羹", jp: "ようかん", romaji: "youkan", en: "Sweet red bean jelly" },
        { kanji: "最中", jp: "もなか", romaji: "monaka", en: "Wafer with bean filling" },
        { jp: "おはぎ", romaji: "ohagi", en: "Sweet rice ball with bean paste" },
        { jp: "ぜんざい", romaji: "zenzai", en: "Sweet red bean porridge" },
        { kanji: "かき氷", jp: "かきごおり", romaji: "kakigoori", en: "Shaved ice" },
      ]),
      sheet("Meat & Protein", [
        { kanji: "肉", jp: "にく", romaji: "niku", en: "Meat" },
        { kanji: "牛肉", jp: "ぎゅうにく", romaji: "gyuuniku", en: "Beef" },
        { kanji: "豚肉", jp: "ぶたにく", romaji: "butaniku", en: "Pork" },
        { kanji: "鶏肉", jp: "とりにく", romaji: "toriniku", en: "Chicken" },
        { kanji: "ひき肉", jp: "ひきにく", romaji: "hikiniku", en: "Ground meat" },
        { jp: "ステーキ", romaji: "suteeki", en: "Steak" },
        { kanji: "焼き肉", jp: "やきにく", romaji: "yakiniku", en: "Grilled meat / BBQ" },
        { jp: "しゃぶしゃぶ", romaji: "shabushabu", en: "Shabu-shabu (hot pot)" },
        { kanji: "すき焼き", jp: "すきやき", romaji: "sukiyaki", en: "Sukiyaki" },
        { jp: "レバー", romaji: "rebaa", en: "Liver" },
        { jp: "ソーセージ", romaji: "sooseeji", en: "Sausage" },
        { jp: "ウインナー", romaji: "uinnaa", en: "Wiener sausage" },
        { jp: "ハム", romaji: "hamu", en: "Ham" },
        { jp: "ベーコン", romaji: "beekon", en: "Bacon" },
        { jp: "ラム", romaji: "ramu", en: "Lamb" },
        { kanji: "鴨", jp: "かも", romaji: "kamo", en: "Duck" },
        { kanji: "卵", jp: "たまご", romaji: "tamago", en: "Egg" },
        { kanji: "ゆで卵", jp: "ゆでたまご", romaji: "yude tamago", en: "Boiled egg" },
        { kanji: "目玉焼き", jp: "めだまやき", romaji: "medamayaki", en: "Fried egg (sunny-side up)" },
        { kanji: "豆腐", jp: "とうふ", romaji: "toufu", en: "Tofu" },
        { kanji: "納豆", jp: "なっとう", romaji: "nattou", en: "Fermented soybeans" },
        { kanji: "大豆", jp: "だいず", romaji: "daizu", en: "Soybeans" },
      ]),
      sheet("Grains, Rice & Bread", [
        { kanji: "米", jp: "こめ", romaji: "kome", en: "Rice (uncooked)" },
        { kanji: "ご飯", jp: "ごはん", romaji: "gohan", en: "Cooked rice / meal" },
        { kanji: "白米", jp: "はくまい", romaji: "hakumai", en: "White rice" },
        { kanji: "玄米", jp: "げんまい", romaji: "genmai", en: "Brown rice" },
        { kanji: "もち米", jp: "もちごめ", romaji: "mochigome", en: "Glutinous rice" },
        { kanji: "餅", jp: "もち", romaji: "mochi", en: "Rice cake (mochi)" },
        { kanji: "食パン", jp: "しょくパン", romaji: "shokupan", en: "Sliced bread (loaf)" },
        { jp: "パン", romaji: "pan", en: "Bread" },
        { jp: "パスタ", romaji: "pasuta", en: "Pasta" },
        { jp: "うどん", romaji: "udon", en: "Udon (thick noodles)" },
        { jp: "そば", romaji: "soba", en: "Soba (buckwheat noodles)" },
        { jp: "ラーメン", romaji: "raamen", en: "Ramen" },
        { jp: "そうめん", romaji: "soumen", en: "Thin wheat noodles" },
        { kanji: "小麦粉", jp: "こむぎこ", romaji: "komugiko", en: "Wheat flour" },
        { jp: "シリアル", romaji: "shiriaru", en: "Cereal" },
        { jp: "オートミール", romaji: "ootomiiru", en: "Oatmeal" },
        { jp: "グラノーラ", romaji: "guranoora", en: "Granola" },
      ]),
      sheet("Spices & Condiments", [
        { kanji: "調味料", jp: "ちょうみりょう", romaji: "choumiryou", en: "Seasonings / condiments" },
        { kanji: "塩", jp: "しお", romaji: "shio", en: "Salt" },
        { kanji: "砂糖", jp: "さとう", romaji: "satou", en: "Sugar" },
        { kanji: "胡椒", jp: "こしょう", romaji: "koshou", en: "Black pepper" },
        { kanji: "酢", jp: "す", romaji: "su", en: "Vinegar" },
        { kanji: "醤油", jp: "しょうゆ", romaji: "shouyu", en: "Soy sauce" },
        { kanji: "味噌", jp: "みそ", romaji: "miso", en: "Miso" },
        { jp: "みりん", romaji: "mirin", en: "Mirin (sweet cooking sake)" },
        { jp: "だし", romaji: "dashi", en: "Dashi (soup stock)" },
        { jp: "マヨネーズ", romaji: "mayoneezu", en: "Mayonnaise" },
        { jp: "ケチャップ", romaji: "kechappu", en: "Ketchup" },
        { jp: "わさび", romaji: "wasabi", en: "Wasabi" },
        { jp: "からし", romaji: "karashi", en: "Japanese mustard" },
        { jp: "ごま", romaji: "goma", en: "Sesame" },
        { kanji: "七味唐辛子", jp: "しちみとうがらし", romaji: "shichimi tougarashi", en: "Seven-spice chili mix" },
        { kanji: "唐辛子", jp: "とうがらし", romaji: "tougarashi", en: "Chili pepper (red)" },
        { kanji: "山椒", jp: "さんしょう", romaji: "sanshou", en: "Japanese pepper (sanshou)" },
      ]),
      sheet("Sauces & Oils", [
        { jp: "ソース", romaji: "soosu", en: "Sauce (tonkatsu / brown)" },
        { jp: "ウスターソース", romaji: "usutaa soosu", en: "Worcestershire sauce" },
        { jp: "とんかつソース", romaji: "tonkatsu soosu", en: "Tonkatsu sauce" },
        { jp: "お好みソース", kanji: "お好みソース", romaji: "okonomi soosu", en: "Okonomiyaki sauce" },
        { jp: "たこ焼きソース", kanji: "たこ焼きソース", romaji: "takoyaki soosu", en: "Takoyaki sauce" },
        { kanji: "ポン酢", jp: "ぽんず", romaji: "ponzu", en: "Ponzu (citrus soy sauce)" },
        { jp: "めんつゆ", romaji: "mentsuyu", en: "Noodle soup base" },
        { jp: "オイスターソース", romaji: "oisutaa soosu", en: "Oyster sauce" },
        { jp: "タルタルソース", romaji: "tarutaru soosu", en: "Tartar sauce" },
        { jp: "ホワイトソース", romaji: "howaito soosu", en: "White sauce (béchamel)" },
        { jp: "チリソース", romaji: "chiri soosu", en: "Chili sauce" },
        { jp: "サルサ", romaji: "sarusa", en: "Salsa" },
        { kanji: "油", jp: "あぶら", romaji: "abura", en: "Oil" },
        { jp: "オリーブオイル", romaji: "oriibu oiru", en: "Olive oil" },
        { kanji: "ごま油", jp: "ごまあぶら", romaji: "goma abura", en: "Sesame oil" },
        { kanji: "サラダ油", jp: "サラダあぶら", romaji: "sarada abura", en: "Vegetable oil" },
        { kanji: "ラー油", jp: "ラーゆ", romaji: "raayu", en: "Chili oil" },
        { jp: "バター", romaji: "bataa", en: "Butter" },
        { jp: "マーガリン", romaji: "maagarin", en: "Margarine" },
      ]),
      sheet("Japanese Cuisine", [
        { kanji: "和食", jp: "わしょく", romaji: "washoku", en: "Japanese cuisine" },
        { kanji: "定食", jp: "ていしょく", romaji: "teishoku", en: "Set meal" },
        { kanji: "味噌汁", jp: "みそしる", romaji: "misoshiru", en: "Miso soup" },
        { kanji: "漬物", jp: "つけもの", romaji: "tsukemono", en: "Pickled vegetables" },
        { kanji: "焼き魚", jp: "やきざかな", romaji: "yakizakana", en: "Grilled fish" },
        { kanji: "刺身", jp: "さしみ", romaji: "sashimi", en: "Sashimi (raw fish)" },
        { kanji: "寿司", jp: "すし", romaji: "sushi", en: "Sushi" },
        { kanji: "巻き寿司", jp: "まきずし", romaji: "makizushi", en: "Rolled sushi" },
        { kanji: "天ぷら", jp: "てんぷら", romaji: "tenpura", en: "Tempura" },
        { kanji: "牛丼", jp: "ぎゅうどん", romaji: "gyuudon", en: "Beef rice bowl" },
        { kanji: "親子丼", jp: "おやこどん", romaji: "oyakodon", en: "Chicken & egg rice bowl" },
        { kanji: "カツ丼", jp: "カツどん", romaji: "katsudon", en: "Pork cutlet rice bowl" },
        { kanji: "うな重", jp: "うなじゅう", romaji: "unajuu", en: "Grilled eel rice box" },
        { kanji: "お好み焼き", jp: "おこのみやき", romaji: "okonomiyaki", en: "Savory pancake" },
        { kanji: "たこ焼き", jp: "たこやき", romaji: "takoyaki", en: "Octopus balls" },
        { kanji: "焼きそば", jp: "やきそば", romaji: "yakisoba", en: "Fried noodles" },
        { kanji: "唐揚げ", jp: "からあげ", romaji: "karaage", en: "Japanese fried chicken" },
        { kanji: "鍋", jp: "なべ", romaji: "nabe", en: "Hot pot" },
        { jp: "コロッケ", romaji: "korokke", en: "Croquette" },
      ]),
      sheet("Western Cuisine", [
        { kanji: "洋食", jp: "ようしょく", romaji: "youshoku", en: "Western cuisine" },
        { jp: "ハンバーグ", romaji: "hanbaagu", en: "Hamburg steak (Salisbury steak)" },
        { jp: "ハンバーガー", romaji: "hanbaagaa", en: "Hamburger" },
        { jp: "ローストビーフ", romaji: "roosuto biifu", en: "Roast beef" },
        { jp: "グラタン", romaji: "guratan", en: "Gratin" },
        { jp: "オムレツ", romaji: "omuretsu", en: "Omelet" },
        { jp: "ポトフ", romaji: "potofu", en: "Pot-au-feu" },
        { jp: "フライドチキン", romaji: "furaido chikin", en: "Fried chicken" },
        { jp: "ベーコンエッグ", romaji: "beekon eggu", en: "Bacon & eggs" },
        { jp: "ピザ", romaji: "piza", en: "Pizza" },
        { jp: "マルゲリータ", romaji: "marugeriita", en: "Margherita pizza" },
        { jp: "ペペロンチーノ", romaji: "peperonchiino", en: "Peperoncino" },
        { jp: "ラザニア", romaji: "razania", en: "Lasagna" },
        { jp: "スパゲッティ", romaji: "supagetti", en: "Spaghetti" },
        { jp: "カルボナーラ", romaji: "karubonaara", en: "Carbonara" },
        { jp: "ミネストローネ", romaji: "minesutoroone", en: "Minestrone" },
        { jp: "パエリア", romaji: "paeria", en: "Paella" },
        { jp: "ドリア", romaji: "doria", en: "Doria (rice gratin)" },
        { jp: "キッシュ", romaji: "kisshu", en: "Quiche" },
        { jp: "オムライス", romaji: "omuraisu", en: "Omelet rice" },
        { jp: "サンドイッチ", romaji: "sandoicchi", en: "Sandwich" },
      ]),
      sheet("Chinese / Korean Cuisine", [
        { kanji: "中華料理", jp: "ちゅうかりょうり", romaji: "chuuka ryouri", en: "Chinese cuisine" },
        { kanji: "餃子", jp: "ぎょうざ", romaji: "gyouza", en: "Dumplings (gyoza)" },
        { kanji: "小籠包", jp: "しょうろんぽう", romaji: "shouronpou", en: "Soup dumplings (xiaolongbao)" },
        { jp: "チャーハン", romaji: "chaahan", en: "Fried rice" },
        { kanji: "麻婆豆腐", jp: "マーボーどうふ", romaji: "maabou doufu", en: "Mapo tofu" },
        { jp: "チンジャオロース", romaji: "chinjao roosu", en: "Stir-fried beef & peppers" },
        { kanji: "酢豚", jp: "すぶた", romaji: "subuta", en: "Sweet & sour pork" },
        { kanji: "春巻き", jp: "はるまき", romaji: "harumaki", en: "Spring roll" },
        { kanji: "肉まん", jp: "にくまん", romaji: "nikuman", en: "Steamed pork bun" },
        { kanji: "担々麺", jp: "たんたんめん", romaji: "tantanmen", en: "Dandan noodles" },
        { jp: "ビビンバ", romaji: "bibinba", en: "Bibimbap" },
        { jp: "キムチ", romaji: "kimuchi", en: "Kimchi" },
        { jp: "チヂミ", romaji: "chijimi", en: "Korean pancake (jeon)" },
        { jp: "プルコギ", romaji: "purukogi", en: "Bulgogi" },
        { jp: "サムギョプサル", romaji: "samugyopusaru", en: "Samgyeopsal (pork belly)" },
        { kanji: "冷麺", jp: "れいめん", romaji: "reimen", en: "Cold noodles" },
        { jp: "キンパ", romaji: "kinpa", en: "Gimbap" },
        { jp: "トッポギ", romaji: "toppogi", en: "Tteokbokki" },
        { jp: "チャプチェ", romaji: "chapuche", en: "Japchae" },
        { jp: "サムゲタン", romaji: "samugetan", en: "Ginseng chicken soup" },
      ]),
      sheet("Convenience Store Items", [
        { jp: "コンビニ", romaji: "konbini", en: "Convenience store" },
        { jp: "おにぎり", romaji: "onigiri", en: "Rice ball" },
        { kanji: "弁当", jp: "べんとう", romaji: "bentou", en: "Bento / lunch box" },
        { jp: "サンドイッチ", romaji: "sandoicchi", en: "Sandwich" },
        { kanji: "カップ麺", jp: "カップめん", romaji: "kappu men", en: "Cup noodles" },
        { kanji: "肉まん", jp: "にくまん", romaji: "nikuman", en: "Steamed pork bun" },
        { jp: "おでん", romaji: "oden", en: "Oden" },
        { jp: "ジュース", romaji: "juusu", en: "Juice" },
        { jp: "コーヒー", romaji: "koohii", en: "Coffee" },
        { kanji: "お茶", jp: "おちゃ", romaji: "ocha", en: "Tea" },
        { kanji: "水", jp: "みず", romaji: "mizu", en: "Water" },
        { jp: "ビール", romaji: "biiru", en: "Beer" },
        { jp: "ティッシュ", romaji: "tisshu", en: "Tissues" },
        { jp: "トイレットペーパー", romaji: "toiretto peepaa", en: "Toilet paper" },
        { jp: "マスク", romaji: "masuku", en: "Face mask" },
        { kanji: "電池", jp: "でんち", romaji: "denchi", en: "Batteries" },
        { jp: "カイロ", romaji: "kairo", en: "Hand warmer" },
        { kanji: "文房具", jp: "ぶんぼうぐ", romaji: "bunbougu", en: "Stationery" },
        { kanji: "傘", jp: "かさ", romaji: "kasa", en: "Umbrella" },
        { jp: "ライター", romaji: "raitaa", en: "Lighter" },
        { kanji: "コピー機", jp: "コピーき", romaji: "kopii ki", en: "Copy machine" },
        { jp: "ATM", romaji: "eetiiemu", en: "ATM" },
        { kanji: "宅配便", jp: "たくはいびん", romaji: "takuhaibin", en: "Delivery service" },
        { kanji: "公共料金", jp: "こうきょうりょうきん", romaji: "koukyou ryoukin", en: "Utility bill payment" },
      ]),
      sheet("Bento Ingredients", [
        { kanji: "弁当", jp: "べんとう", romaji: "bentou", en: "Bento (lunch box)" },
        { kanji: "ご飯", jp: "ごはん", romaji: "gohan", en: "Rice" },
        { jp: "ふりかけ", romaji: "furikake", en: "Rice seasoning" },
        { kanji: "梅干し", jp: "うめぼし", romaji: "umeboshi", en: "Pickled plum" },
        { kanji: "卵焼き", jp: "たまごやき", romaji: "tamagoyaki", en: "Sweet rolled omelette" },
        { kanji: "唐揚げ", jp: "からあげ", romaji: "karaage", en: "Fried chicken" },
        { jp: "ウインナー", romaji: "uinnaa", en: "Sausage (wiener)" },
        { kanji: "照り焼きチキン", jp: "てりやきチキン", romaji: "teriyaki chikin", en: "Teriyaki chicken" },
        { jp: "ハンバーグ", romaji: "hanbaagu", en: "Hamburger steak" },
        { jp: "ミートボール", romaji: "miitobooru", en: "Meatball" },
        { jp: "きんぴらごぼう", romaji: "kinpira gobou", en: "Sautéed burdock root" },
        { kanji: "煮物", jp: "にもの", romaji: "nimono", en: "Simmered vegetables" },
        { jp: "ポテトサラダ", romaji: "poteto sarada", en: "Potato salad" },
        { jp: "マカロニサラダ", romaji: "makaroni sarada", en: "Macaroni salad" },
        { jp: "ミニトマト", romaji: "mini tomato", en: "Cherry tomato" },
        { jp: "ちくわ", romaji: "chikuwa", en: "Fish cake tube" },
        { jp: "かまぼこ", romaji: "kamaboko", en: "Steamed fish cake" },
        { jp: "コロッケ", romaji: "korokke", en: "Croquette" },
        { kanji: "エビフライ", jp: "えびフライ", romaji: "ebi furai", en: "Fried shrimp" },
        { jp: "たくあん", romaji: "takuan", en: "Pickled daikon" },
        { jp: "ナポリタン", romaji: "naporitan", en: "Ketchup spaghetti" },
      ]),
      sheet("Street Food & Festivals", [
        { kanji: "屋台", jp: "やたい", romaji: "yatai", en: "Food stall" },
        { kanji: "縁日", jp: "えんにち", romaji: "ennichi", en: "Temple fair" },
        { kanji: "お祭り", jp: "おまつり", romaji: "omatsuri", en: "Festival" },
        { kanji: "たこ焼き", jp: "たこやき", romaji: "takoyaki", en: "Octopus balls" },
        { kanji: "お好み焼き", jp: "おこのみやき", romaji: "okonomiyaki", en: "Savory pancake" },
        { kanji: "焼きそば", jp: "やきそば", romaji: "yakisoba", en: "Fried noodles" },
        { jp: "じゃがバター", romaji: "jaga bataa", en: "Buttered potato" },
        { kanji: "焼きとうもろこし", jp: "やきとうもろこし", romaji: "yaki toumorokoshi", en: "Grilled corn" },
        { jp: "チョコバナナ", romaji: "chokobanana", en: "Chocolate banana" },
        { kanji: "たい焼き", jp: "たいやき", romaji: "taiyaki", en: "Fish-shaped cake" },
        { kanji: "かき氷", jp: "かきごおり", romaji: "kakigoori", en: "Shaved ice" },
        { kanji: "綿菓子", jp: "わたがし", romaji: "watagashi", en: "Cotton candy" },
        { kanji: "焼き鳥", jp: "やきとり", romaji: "yakitori", en: "Grilled chicken skewers" },
        { kanji: "りんご飴", jp: "りんごあめ", romaji: "ringo ame", en: "Candy apple" },
        { kanji: "金魚すくい", jp: "きんぎょすくい", romaji: "kingyo sukui", en: "Goldfish scooping" },
        { kanji: "花火", jp: "はなび", romaji: "hanabi", en: "Fireworks" },
        { kanji: "浴衣", jp: "ゆかた", romaji: "yukata", en: "Yukata (summer kimono)" },
      ]),
      sheet("Izakaya", [
        { kanji: "居酒屋", jp: "いざかや", romaji: "izakaya", en: "Japanese-style pub" },
        { kanji: "お通し", jp: "おとおし", romaji: "otooshi", en: "Appetizer / table charge" },
        { kanji: "飲み放題", jp: "のみほうだい", romaji: "nomihoudai", en: "All-you-can-drink" },
        { kanji: "食べ放題", jp: "たべほうだい", romaji: "tabehoudai", en: "All-you-can-eat" },
        { kanji: "枝豆", jp: "えだまめ", romaji: "edamame", en: "Edamame" },
        { kanji: "冷奴", jp: "ひややっこ", romaji: "hiyayakko", en: "Cold tofu" },
        { kanji: "唐揚げ", jp: "からあげ", romaji: "karaage", en: "Fried chicken" },
        { kanji: "焼き鳥", jp: "やきとり", romaji: "yakitori", en: "Grilled chicken skewers" },
        { kanji: "刺身", jp: "さしみ", romaji: "sashimi", en: "Sashimi" },
        { kanji: "だし巻き卵", jp: "だしまきたまご", romaji: "dashimaki tamago", en: "Rolled omelette" },
        { jp: "ポテトフライ", romaji: "poteto furai", en: "French fries" },
        { jp: "ハイボール", romaji: "haibooru", en: "Highball" },
        { jp: "レモンサワー", romaji: "remon sawaa", en: "Lemon sour" },
        { kanji: "生ビール", jp: "なまビール", romaji: "nama biiru", en: "Draft beer" },
        { kanji: "日本酒", jp: "にほんしゅ", romaji: "nihonshu", en: "Sake" },
        { kanji: "お会計", jp: "おかいけい", romaji: "okaikei", en: "Check / bill" },
        { kanji: "乾杯", jp: "かんぱい", romaji: "kanpai", en: "Cheers / toast" },
        { jp: "ごちそうさまでした", romaji: "gochisousama deshita", en: "Thanks for the meal" },
      ]),
      sheet("Cafe", [
        { jp: "カフェ", romaji: "kafe", en: "Cafe" },
        { kanji: "喫茶店", jp: "きっさてん", romaji: "kissaten", en: "Traditional cafe" },
        { jp: "コーヒー", romaji: "koohii", en: "Coffee" },
        { jp: "アイスコーヒー", romaji: "aisu koohii", en: "Iced coffee" },
        { jp: "カフェラテ", romaji: "kafe rate", en: "Cafe latte" },
        { jp: "エスプレッソ", romaji: "esupuresso", en: "Espresso" },
        { kanji: "紅茶", jp: "こうちゃ", romaji: "koucha", en: "Black tea" },
        { jp: "ミルクティー", romaji: "miruku tii", en: "Milk tea" },
        { kanji: "抹茶", jp: "まっちゃ", romaji: "matcha", en: "Matcha" },
        { jp: "スムージー", romaji: "sumuujii", en: "Smoothie" },
        { jp: "ケーキ", romaji: "keeki", en: "Cake" },
        { jp: "ケーキセット", romaji: "keeki setto", en: "Cake set" },
        { jp: "パンケーキ", romaji: "pankeeki", en: "Pancake" },
        { jp: "モーニング", romaji: "mooningu", en: "Morning set (breakfast)" },
        { jp: "ランチ", romaji: "ranchi", en: "Lunch set" },
        { jp: "テイクアウト", romaji: "teikuauto", en: "Takeout" },
        { kanji: "店内", jp: "てんない", romaji: "tennai", en: "Dine-in" },
        { jp: "コンセント", romaji: "konsento", en: "Power outlet" },
      ]),
      sheet("Delivery & Takeout", [
        { jp: "デリバリー", romaji: "deribarii", en: "Delivery" },
        { kanji: "出前", jp: "でまえ", romaji: "demae", en: "Food delivery (traditional)" },
        { kanji: "持ち帰り", jp: "もちかえり", romaji: "mochikaeri", en: "Takeout" },
        { jp: "テイクアウト", romaji: "teikuauto", en: "Takeout" },
        { jp: "ウーバーイーツ", romaji: "uubaa iitsu", en: "Uber Eats" },
        { kanji: "出前館", jp: "でまえかん", romaji: "demaekan", en: "Demae-kan (delivery app)" },
        { kanji: "配達", jp: "はいたつ", romaji: "haitatsu", en: "Delivery" },
        { kanji: "配達料", jp: "はいたつりょう", romaji: "haitatsu ryou", en: "Delivery fee" },
        { kanji: "注文", jp: "ちゅうもん", romaji: "chuumon", en: "Order" },
        { kanji: "オンライン注文", jp: "オンラインちゅうもん", romaji: "onrain chuumon", en: "Online order" },
        { kanji: "電話注文", jp: "でんわちゅうもん", romaji: "denwa chuumon", en: "Phone order" },
        { kanji: "容器", jp: "ようき", romaji: "youki", en: "Container" },
        { kanji: "割り箸", jp: "わりばし", romaji: "waribashi", en: "Disposable chopsticks" },
        { jp: "レシート", romaji: "reshiito", en: "Receipt" },
      ]),
      sheet("Allergies & Dietary Needs", [
        { jp: "アレルギー", romaji: "arerugii", en: "Allergy" },
        { kanji: "食物アレルギー", jp: "しょくもつアレルギー", romaji: "shokumotsu arerugii", en: "Food allergy" },
        { kanji: "食事制限", jp: "しょくじせいげん", romaji: "shokuji seigen", en: "Dietary restriction" },
        { jp: "ベジタリアン", romaji: "bejitarian", en: "Vegetarian" },
        { jp: "ビーガン", romaji: "biigan", en: "Vegan" },
        { jp: "グルテンフリー", romaji: "guruten furii", en: "Gluten-free" },
        { kanji: "卵", jp: "たまご", romaji: "tamago", en: "Egg" },
        { kanji: "乳", jp: "にゅう", romaji: "nyuu", en: "Milk / dairy" },
        { kanji: "小麦", jp: "こむぎ", romaji: "komugi", en: "Wheat" },
        { jp: "そば", romaji: "soba", en: "Buckwheat" },
        { kanji: "落花生", jp: "らっかせい", romaji: "rakkasei", en: "Peanut" },
        { jp: "えび", romaji: "ebi", en: "Shrimp" },
        { jp: "かに", romaji: "kani", en: "Crab" },
        { kanji: "大豆", jp: "だいず", romaji: "daizu", en: "Soybean" },
        { jp: "ハラル", romaji: "hararu", en: "Halal" },
        { kanji: "〜抜きでお願いします", jp: "〜ぬきでおねがいします", romaji: "~nuki de onegaishimasu", en: "Without ~, please" },
        { kanji: "〜が入っていますか", jp: "〜がはいっていますか", romaji: "~ga haitte imasu ka", en: "Does it contain ~?" },
      ]),
    ],
  },
  {
    slug: "travel",
    label: "Travel & Tourism",
    emoji: "✈️",
    accent: "blue",
    subjects: [
      sheet("At the Airport", [
        { kanji: "空港", jp: "くうこう", romaji: "kuukou", en: "Airport" },
        { jp: "ターミナル", romaji: "taaminaru", en: "Terminal" },
        { kanji: "国際線", jp: "こくさいせん", romaji: "kokusaisen", en: "International flight" },
        { kanji: "国内線", jp: "こくないせん", romaji: "kokunaisen", en: "Domestic flight" },
        { kanji: "搭乗券", jp: "とうじょうけん", romaji: "toujouken", en: "Boarding pass" },
        { kanji: "搭乗ゲート", jp: "とうじょうゲート", romaji: "toujou geeto", en: "Boarding gate" },
        { kanji: "出国", jp: "しゅっこく", romaji: "shukkoku", en: "Departure (leaving the country)" },
        { kanji: "入国審査", jp: "にゅうこくしんさ", romaji: "nyuukoku shinsa", en: "Immigration" },
        { kanji: "税関", jp: "ぜいかん", romaji: "zeikan", en: "Customs" },
        { kanji: "免税店", jp: "めんぜいてん", romaji: "menzeiten", en: "Duty-free shop" },
        { jp: "パスポート", romaji: "pasupooto", en: "Passport" },
        { kanji: "手荷物", jp: "てにもつ", romaji: "tenimotsu", en: "Hand luggage" },
        { kanji: "遅延", jp: "ちえん", romaji: "chien", en: "Delay" },
      ]),
      sheet("Transportation", [
        { kanji: "交通", jp: "こうつう", romaji: "koutsuu", en: "Transportation" },
        { kanji: "乗り物", jp: "のりもの", romaji: "norimono", en: "Vehicle / ride" },
        { kanji: "電車", jp: "でんしゃ", romaji: "densha", en: "Train" },
        { kanji: "地下鉄", jp: "ちかてつ", romaji: "chikatetsu", en: "Subway" },
        { kanji: "新幹線", jp: "しんかんせん", romaji: "shinkansen", en: "Bullet train (Shinkansen)" },
        { jp: "バス", romaji: "basu", en: "Bus" },
        { kanji: "高速バス", jp: "こうそくバス", romaji: "kousoku basu", en: "Long-distance bus" },
        { jp: "タクシー", romaji: "takushii", en: "Taxi" },
        { kanji: "自転車", jp: "じてんしゃ", romaji: "jitensha", en: "Bicycle" },
        { jp: "レンタサイクル", romaji: "rentasaikuru", en: "Rental bicycle" },
        { jp: "バイク", romaji: "baiku", en: "Motorcycle" },
        { kanji: "車", jp: "くるま", romaji: "kuruma", en: "Car" },
        { jp: "レンタカー", romaji: "rentakaa", en: "Rental car" },
        { kanji: "運転", jp: "うんてん", romaji: "unten", en: "Driving" },
        { kanji: "駅", jp: "えき", romaji: "eki", en: "Station" },
        { kanji: "切符", jp: "きっぷ", romaji: "kippu", en: "Ticket" },
        { kanji: "改札", jp: "かいさつ", romaji: "kaisatsu", en: "Ticket gate" },
        { jp: "ホーム", romaji: "hoomu", en: "Platform" },
        { kanji: "時刻表", jp: "じこくひょう", romaji: "jikokuhyou", en: "Timetable" },
        { kanji: "路線図", jp: "ろせんず", romaji: "rosenzu", en: "Route map" },
        { kanji: "乗り換え", jp: "のりかえ", romaji: "norikae", en: "Transfer (trains)" },
        { kanji: "出口", jp: "でぐち", romaji: "deguchi", en: "Exit" },
        { kanji: "入口", jp: "いりぐち", romaji: "iriguchi", en: "Entrance" },
        { kanji: "飛行機", jp: "ひこうき", romaji: "hikouki", en: "Airplane" },
        { kanji: "船", jp: "ふね", romaji: "fune", en: "Ship / boat" },
        { kanji: "急行", jp: "きゅうこう", romaji: "kyuukou", en: "Express train" },
        { kanji: "特急", jp: "とっきゅう", romaji: "tokkyuu", en: "Limited express" },
        { kanji: "終電", jp: "しゅうでん", romaji: "shuuden", en: "Last train" },
        { kanji: "始発", jp: "しはつ", romaji: "shihatsu", en: "First train" },
      ]),
      sheet("Sightseeing Words", [
        { kanji: "観光", jp: "かんこう", romaji: "kankou", en: "Sightseeing / tourism" },
        { kanji: "観光地", jp: "かんこうち", romaji: "kankouchi", en: "Tourist spot" },
        { kanji: "名所", jp: "めいしょ", romaji: "meisho", en: "Famous place" },
        { kanji: "景色", jp: "けしき", romaji: "keshiki", en: "Scenery / view" },
        { kanji: "絶景", jp: "ぜっけい", romaji: "zekkei", en: "Breathtaking view" },
        { kanji: "神社", jp: "じんじゃ", romaji: "jinja", en: "Shrine" },
        { kanji: "お寺", jp: "おてら", romaji: "otera", en: "Temple" },
        { kanji: "城", jp: "しろ", romaji: "shiro", en: "Castle" },
        { kanji: "博物館", jp: "はくぶつかん", romaji: "hakubutsukan", en: "Museum" },
        { kanji: "美術館", jp: "びじゅつかん", romaji: "bijutsukan", en: "Art museum" },
        { kanji: "水族館", jp: "すいぞくかん", romaji: "suizokukan", en: "Aquarium" },
        { kanji: "動物園", jp: "どうぶつえん", romaji: "doubutsuen", en: "Zoo" },
        { kanji: "展望台", jp: "てんぼうだい", romaji: "tenboudai", en: "Observation deck" },
        { kanji: "庭園", jp: "ていえん", romaji: "teien", en: "Garden" },
        { kanji: "公園", jp: "こうえん", romaji: "kouen", en: "Park" },
        { kanji: "温泉", jp: "おんせん", romaji: "onsen", en: "Hot spring" },
        { kanji: "入場料", jp: "にゅうじょうりょう", romaji: "nyuujou ryou", en: "Admission fee" },
        { jp: "ガイド", romaji: "gaido", en: "Guide" },
        { jp: "ガイドブック", romaji: "gaidobukku", en: "Guidebook" },
        { jp: "ツアー", romaji: "tsuaa", en: "Tour" },
        { kanji: "地図", jp: "ちず", romaji: "chizu", en: "Map" },
        { kanji: "お土産", jp: "おみやげ", romaji: "omiyage", en: "Souvenir" },
        { kanji: "写真を撮る", jp: "しゃしんをとる", romaji: "shashin o toru", en: "Take a photo" },
      ]),
      sheet("Hotels & Ryokan", [
        { jp: "ホテル", romaji: "hoteru", en: "Hotel" },
        { kanji: "旅館", jp: "りょかん", romaji: "ryokan", en: "Japanese inn (ryokan)" },
        { kanji: "民宿", jp: "みんしゅく", romaji: "minshuku", en: "Guesthouse / B&B" },
        { jp: "ゲストハウス", romaji: "gesuto hausu", en: "Guesthouse" },
        { jp: "カプセルホテル", romaji: "kapuseru hoteru", en: "Capsule hotel" },
        { jp: "ビジネスホテル", romaji: "bijinesu hoteru", en: "Business hotel" },
        { jp: "チェックイン", romaji: "chekkuin", en: "Check-in" },
        { jp: "チェックアウト", romaji: "chekkuauto", en: "Check-out" },
        { kanji: "予約", jp: "よやく", romaji: "yoyaku", en: "Reservation" },
        { jp: "フロント", romaji: "furonto", en: "Front desk / reception" },
        { kanji: "部屋", jp: "へや", romaji: "heya", en: "Room" },
        { jp: "シングル", romaji: "shinguru", en: "Single room" },
        { jp: "ツイン", romaji: "tsuin", en: "Twin room" },
        { kanji: "和室", jp: "わしつ", romaji: "washitsu", en: "Japanese-style room" },
        { kanji: "洋室", jp: "ようしつ", romaji: "youshitsu", en: "Western-style room" },
        { kanji: "布団", jp: "ふとん", romaji: "futon", en: "Futon" },
        { kanji: "露天風呂", jp: "ろてんぶろ", romaji: "rotenburo", en: "Open-air bath" },
        { kanji: "大浴場", jp: "だいよくじょう", romaji: "daiyokujou", en: "Large public bath" },
        { kanji: "朝食付き", jp: "ちょうしょくつき", romaji: "choushoku tsuki", en: "Breakfast included" },
        { kanji: "空室", jp: "くうしつ", romaji: "kuushitsu", en: "Vacancy" },
      ]),
      sheet("Tourist Attractions", [
        { kanji: "観光名所", jp: "かんこうめいしょ", romaji: "kankou meisho", en: "Tourist attraction" },
        { kanji: "観光スポット", jp: "かんこうスポット", romaji: "kankou supotto", en: "Sightseeing spot" },
        { kanji: "人気スポット", jp: "にんきスポット", romaji: "ninki supotto", en: "Popular spot" },
        { kanji: "穴場スポット", jp: "あなばスポット", romaji: "anaba supotto", en: "Hidden gem" },
        { kanji: "展望台", jp: "てんぼうだい", romaji: "tenboudai", en: "Observation deck" },
        { kanji: "城", jp: "しろ", romaji: "shiro", en: "Castle" },
        { kanji: "寺", jp: "てら", romaji: "tera", en: "Buddhist temple" },
        { kanji: "仏像", jp: "ぶつぞう", romaji: "butsuzou", en: "Buddha statue" },
        { kanji: "神社", jp: "じんじゃ", romaji: "jinja", en: "Shrine" },
        { kanji: "鳥居", jp: "とりい", romaji: "torii", en: "Torii gate" },
        { kanji: "庭園", jp: "ていえん", romaji: "teien", en: "Garden" },
        { kanji: "滝", jp: "たき", romaji: "taki", en: "Waterfall" },
        { kanji: "湖", jp: "みずうみ", romaji: "mizuumi", en: "Lake" },
      ]),
      sheet("Luggage & Packing", [
        { kanji: "荷物", jp: "にもつ", romaji: "nimotsu", en: "Luggage / baggage" },
        { jp: "スーツケース", romaji: "suutsukeesu", en: "Suitcase" },
        { jp: "キャリーバッグ", romaji: "kyarii baggu", en: "Rolling luggage" },
        { jp: "バックパック", romaji: "bakkupakku", en: "Backpack" },
        { jp: "リュック", romaji: "ryukku", en: "Daypack / backpack" },
        { jp: "かばん", romaji: "kaban", en: "Bag" },
        { jp: "ボストンバッグ", romaji: "bosuton baggu", en: "Duffel bag" },
        { jp: "パスポート", romaji: "pasupooto", en: "Passport" },
        { kanji: "財布", jp: "さいふ", romaji: "saifu", en: "Wallet" },
        { kanji: "充電器", jp: "じゅうでんき", romaji: "juudenki", en: "Charger" },
        { kanji: "変換プラグ", jp: "へんかんプラグ", romaji: "henkan puragu", en: "Plug adapter" },
        { jp: "モバイルバッテリー", romaji: "mobairu batterii", en: "Portable charger" },
        { kanji: "歯ブラシ", jp: "はブラシ", romaji: "haburashi", en: "Toothbrush" },
        { jp: "タオル", romaji: "taoru", en: "Towel" },
        { kanji: "着替え", jp: "きがえ", romaji: "kigae", en: "Change of clothes" },
        { jp: "アイマスク", romaji: "aimasuku", en: "Eye mask" },
        { jp: "ネックピロー", romaji: "nekku piroo", en: "Neck pillow" },
        { kanji: "洗面用具", jp: "せんめんようぐ", romaji: "senmen yougu", en: "Toiletries" },
      ]),
      sheet("Useful Emergency Phrases", [
        { kanji: "助けて", jp: "たすけて", romaji: "tasukete", en: "Help!" },
        { kanji: "助けてください", jp: "たすけてください", romaji: "tasukete kudasai", en: "Please help me" },
        { kanji: "警察を呼んでください", jp: "けいさつをよんでください", romaji: "keisatsu o yonde kudasai", en: "Please call the police" },
        { kanji: "救急車を呼んでください", jp: "きゅうきゅうしゃをよんでください", romaji: "kyuukyuusha o yonde kudasai", en: "Please call an ambulance" },
        { kanji: "道に迷いました", jp: "みちにまよいました", romaji: "michi ni mayoimashita", en: "I'm lost" },
        { kanji: "財布をなくしました", jp: "さいふをなくしました", romaji: "saifu o nakushimashita", en: "I lost my wallet" },
        { jp: "パスポートをなくしました", romaji: "pasupooto o nakushimashita", en: "I lost my passport" },
        { kanji: "気分が悪いです", jp: "きぶんがわるいです", romaji: "kibun ga warui desu", en: "I feel sick" },
        { kanji: "病院はどこですか", jp: "びょういんはどこですか", romaji: "byouin wa doko desu ka", en: "Where is the hospital?" },
        { kanji: "英語が話せる人はいますか", jp: "えいごがはなせるひとはいますか", romaji: "eigo ga hanaseru hito wa imasu ka", en: "Does anyone speak English?" },
        { kanji: "大丈夫ですか", jp: "だいじょうぶですか", romaji: "daijoubu desu ka", en: "Are you okay?" },
        { kanji: "危ない", jp: "あぶない", romaji: "abunai", en: "Look out! / Dangerous" },
      ]),
      ...soon("Directions & Maps"),
    ],
  },
  {
    slug: "public",
    label: "Public Life & Services",
    emoji: "🏛️",
    accent: "mint",
    subjects: [
      sheet("Banking & ATMs", [
        { kanji: "銀行", jp: "ぎんこう", romaji: "ginkou", en: "Bank" },
        { kanji: "口座", jp: "こうざ", romaji: "kouza", en: "Bank account" },
        { kanji: "通帳", jp: "つうちょう", romaji: "tsuuchou", en: "Bankbook / passbook" },
        { kanji: "印鑑", jp: "いんかん", romaji: "inkan", en: "Seal / personal stamp" },
        { kanji: "暗証番号", jp: "あんしょうばんごう", romaji: "anshou bangou", en: "PIN" },
        { kanji: "引き出す", jp: "ひきだす", romaji: "hikidasu", en: "To withdraw" },
        { kanji: "預ける", jp: "あずける", romaji: "azukeru", en: "To deposit" },
        { kanji: "振り込み", jp: "ふりこみ", romaji: "furikomi", en: "Bank transfer" },
        { kanji: "残高", jp: "ざんだか", romaji: "zandaka", en: "Balance" },
        { kanji: "手数料", jp: "てすうりょう", romaji: "tesuuryou", en: "Fee / commission" },
        { kanji: "両替", jp: "りょうがえ", romaji: "ryougae", en: "Currency exchange" },
        { kanji: "為替レート", jp: "かわせレート", romaji: "kawase reeto", en: "Exchange rate" },
        { kanji: "窓口", jp: "まどぐち", romaji: "madoguchi", en: "Teller window" },
        { jp: "キャッシュカード", romaji: "kyasshu kaado", en: "Cash card" },
        { jp: "クレジットカード", romaji: "kurejitto kaado", en: "Credit card" },
        { jp: "ローン", romaji: "roon", en: "Loan" },
        { kanji: "利子", jp: "りし", romaji: "rishi", en: "Interest" },
        { jp: "ATM", romaji: "eetiiemu", en: "ATM" },
      ]),
      ...soon(
        "Immigration & Embassy", "Police & Safety", "Fire & Ambulance",
        "Pharmacy & Medications", "Insurance & Health Terms", "City Hall & Paperwork",
        "Garbage & Recycling Rules"
      ),
    ],
  },
  {
    slug: "education",
    label: "Education & Career",
    emoji: "🎓",
    accent: "pink",
    subjects: soon(
      "Classroom Objects", "School Subjects", "School Life & Schedule", "University & Exams",
      "Jobs & Occupations", "Workplace Vocabulary", "Business Etiquette",
      "Company Hierarchy", "Emails & Formal Phrases"
    ),
  },
  {
    slug: "social",
    label: "Social & Identity",
    emoji: "🧑‍🤝‍🧑",
    accent: "lilac",
    subjects: soon(
      "Countries & Nationalities", "Languages", "Family & Relatives",
      "Relationships & Dating", "Gender", "Pronouns", "Personality Traits",
      "Emotions & Feelings", "Politics"
    ),
  },
  {
    slug: "nature",
    label: "Nature & Seasons",
    emoji: "🌿",
    accent: "mint",
    subjects: soon(
      "Pets", "Insects", "Sea Creatures", "Flowers & Trees", "Weather",
      "Seasons & Events", "Natural Disasters", "Mountains, Rivers, Lakes"
    ),
  },
  {
    slug: "leisure",
    label: "Leisure & Entertainment",
    emoji: "🎮",
    accent: "blue",
    subjects: soon(
      "Music & Instruments", "Concerts & Events", "Anime & Manga", "Video Games",
      "Theme Parks", "Nightlife & Bars", "Hobbies", "DIY & Crafts",
      "Reading & Books", "Movies & Theater"
    ),
  },
  {
    slug: "conversation",
    label: "Conversation & Slang",
    emoji: "💬",
    accent: "gold",
    subjects: soon(
      "Casual Phrases", "Dialects", "Filler Words", "Speech Style Differences",
      "Counters", "Onomatopoeia", "Time Words", "Conjunctions"
    ),
  },
];

// Flattened pool of all transcribed words (used by mini-games & search).
export const allWords: Word[] = (() => {
  const seen = new Set<string>();
  const out: Word[] = [];
  for (const c of vocabCategories)
    for (const s of c.subjects)
      for (const w of s.words)
        if (!seen.has(w.jp)) {
          seen.add(w.jp);
          out.push(w);
        }
  return out;
})();

export const totalWords = allWords.length;
export const totalSubjects = vocabCategories.reduce((n, c) => n + c.subjects.length, 0);
export const readySubjects = vocabCategories.reduce(
  (n, c) => n + c.subjects.filter((s) => s.words.length > 0).length,
  0
);
